### ISSUE TITLE
cygwin support

### ISSUE THREAD

**Issue by geekyme** [panosoft/elm-grove#15]
I am having the below error when I install using grove in an elm project.

```
$ grove install
Cloning https://github.com/elm-lang/core.git
Cloning https://github.com/elm-lang/html.git
ERROR: Unable to clone: elm-lang/core Error: Unable to clone: https://github.com/elm-lang/core.git (Error: failed to make directory 'C:\workspace\ext\cygwin\tmp\elm-lang\core': The system cannot find the path specified.
)
ERROR: Unable to clone: elm-lang/html Error: Unable to clone: https://github.com/elm-lang/html.git (Error: failed to make directory 'C:\workspace\ext\cygwin\tmp\elm-lang\html': The system cannot find the path specified.
)
```

**Comment by cscalfani** [comment]
First of all, Windows has not been tested and neither has `cygwin` under Windows. (See [Known Issues](https://github.com/panosoft/elm-grove#known-issues) )

Second of all, the error is right there in the error message. It cannot make the directory: `C:\workspace\ext\cygwin\tmp\elm-lang\core` since the path is bad. That tells me that that your temporary directory is bad.

Grove uses your temporary directory to do it's work. It uses node's `os.tmpdir` call to get the temporary directory's location. It appears that `C:\workspace\ext\cygwin\tmp` is the value that's returned from that call which, IIRC, is taken from the environment variable `$TMPDIR`.

For some reason, it appears that `C:\workspace\ext\cygwin\tmp` doesn't exist.

**Comment by geekyme** [comment]
Just verified that the temp directory is there:

```
boo@com1 /tmp/elm-lang
$ ls
total 384K
drwxr-xr-x+ 1 boo Domain Users 0 Nov 22 09:09 .
drwxr-xr-x+ 1 boo Domain Users 0 Nov 22 09:08 ..
drwxr-xr-x+ 1 boo Domain Users 0 Nov 22 09:08 core
drwxr-xr-x+ 1 boo Domain Users 0 Nov 22 09:09 html

boo@com1 /tmp/elm-lang
$ pwd
/tmp/elm-lang

boo@com1 /tmp/elm-lang
$ cygpath -w $(pwd)
C:\workspace\ext\cygwin\tmp\elm-lang

boo@com1 /tmp/elm-lang
$

```

**Comment by cscalfani** [comment]
You're testing the directory inside of `cygwin`, which is relative to the *nix environment and deals with a path that has an implied root, viz. the cygwin root, but the path printed by Grove is absolute path from a Windows perspective.

See if `C:\workspace\ext\cygwin\tmp` exists from `cmd`.

**Comment by geekyme** [comment]
yes it exists.
```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\1569800>cd C:\workspace\ext\cygwin\tmp

C:\workspace\ext\cygwin\tmp>
```

**Comment by cscalfani** [comment]
Okay, that's good to know...

Now, the odd thing here is that we are getting a Windows path when running inside of `cygwin`.  It's possible that this is the source of the error.

Below is the `os.tmpdir` code from `node`. I'm not sure what `isWindows` is since it's probably within the closure of that function, but I wonder what it's value is when run under `cygwin`.

It may be worth playing with `os.tmpdir` in node run from a `cygwin` prompt to see.

```js
function tmpdir() {
  var path;
  if (isWindows) {
    path = process.env.TEMP ||
           process.env.TMP ||
           (process.env.SystemRoot || process.env.windir) + '\\temp';
    if (path.length > 1 && path.endsWith('\\') && !path.endsWith(':\\'))
      path = path.slice(0, -1);
  } else {
    path = process.env.TMPDIR ||
           process.env.TMP ||
           process.env.TEMP ||
           '/tmp';
    if (path.length > 1 && path.endsWith('/'))
      path = path.slice(0, -1);
  }

  return path;
}
```

**Comment by geekyme** [comment]
Ok here's the result:

```
$ cat test.js
const os = require('os');

console.log(os.tmpdir());
```

```
$ node test.js
C:\workspace\ext\cygwin\tmp
```

**Comment by cscalfani** [comment]
It looks like it's getting the value from `process.env.TMP` or `process.env.TEMP`. See if you can set these variables inside `cygwin` to your `/tmp` directory. Hopefully, it'll override the Windows environment variables.

**Comment by geekyme** [comment]
```
bob@com1 ~/experiments/test-grove
$ export TMP=/tmp

bob@com1 ~/experiments/test-grove
$ node test
C:\workspace\ext\cygwin\tmp

bob@com1 ~/experiments/test-grove
$ echo $TMP
/tmp

bob@com1 ~/experiments/test-grove
$ echo $TEMP
/tmp
```

**Comment by cscalfani** [comment]
So after a bit of testing and research, I've come to the conclusion that running under `cygwin` is problematic at best, horrible at worst.

`npm` doesn't seem to support `cygwin` and `node`'s REPL doesn't seem to work either. Basically, you're just fighting an uphill battle.

I'd suggest running under a VM that's running Linux or try running in Windows where `node` and `npm` do work and are supported.
