### ISSUE TITLE
Numbers not allowed in repo name

### ISSUE THREAD

**Issue by cmditch** [panosoft/elm-grove#9]
When adding my repo "elm-web3", I get `error:   Invalid repo name... must be like: your-user-name/your-repo-name`

**Comment by cscalfani** [comment]
I assuming that you are executing `grove init`. When you name your repo it must be in the correct form as specified by the error message, e.g. a valid name would be `panosoft/elm-grove` whereas `grove` would NOT be.

**Comment by cmditch** [comment]
Indeed, cmditch/elm-web3 is considered invalid.

**Comment by cmditch** [comment]
Might be affecting this as well, 
![image](https://user-images.githubusercontent.com/15849320/32349019-1a4869e4-bfec-11e7-8183-5147d31b6946.png)

**Comment by cmditch** [comment]
#10

**Comment by cscalfani** [comment]
The error you encountered is a bug in the regular expression for the repo portion of the name. I'm in the process of making a new release in less than a week and I'll have a fix for it then.

A workaround is to leave the number off and then edit the `elm-package.json` by hand to add the number back.

The second error message is because of validation that's done on `package.json`. This check will NOT be done if there are NO dependencies but for some odd reason `Skinney/murmur3` has them even though it shouldn't since the only dependency is for test. The dependencies should be `devDependencies`.

Unfortunately, there is no workaround for this issue.

Looks like I'll have to make it a WARNING instead of an ERROR.

**Comment by cscalfani** [comment]
Both issues mentioned here are fixed in 1.2.0.
